In [1]:
# T02_01.py
import numpy as np

x = [4, 3, 2, 1] # ①
y = np.array(x).reshape(-1, 2) # ②
print(y)
z = np.array(x).reshape(-1, 1) # ③
print(z)

[[4 3]
 [2 1]]
[[4]
 [3]
 [2]
 [1]]


In [2]:
# T02_02.py
from sklearn.linear_model import LinearRegression
import numpy as np

# 데이터 준비
study_hours = [1, 4, 2, 3] # 공부 시간(독립변수)
test_scores = [16, 29, 17, 28] # 시험 점수(종속변수)

# sklearn 요구 형태로 변환
X = np.array(study_hours).reshape(-1, 1) # ①
y = np.array(test_scores) # ②

# 모델 객체 생성
model = LinearRegression() # ③

# 모델 학습
model.fit(X, y) # ④
print(f"y = {model.coef_[0]:.2f}x + {model.intercept_:.2f}")

# 예측 수행
predictions = model.predict(X) # ⑤
for i in range(0, len(study_hours)):
 print(f"x={study_hours[i]}: y 실제={test_scores[i]}, y 예측={predictions[i]:.1f}")

y = 5.00x + 10.00
x=1: y 실제=16, y 예측=15.0
x=4: y 실제=29, y 예측=30.0
x=2: y 실제=17, y 예측=20.0
x=3: y 실제=28, y 예측=25.0


In [3]:
# T02_03.py
new_hours = [6, 7, 8]
new_X = np.array(new_hours).reshape(-1, 1) # ①
new_predictions = model.predict(new_X) # ②

for i in range(0, len(new_hours)):
  print(f"x={new_hours[i]}: y 예측={new_predictions[i]:.1f}") # ③

x=6: y 예측=40.0
x=7: y 예측=45.0
x=8: y 예측=50.0


In [4]:
# T02_04.py
import numpy as np
from sklearn.metrics import mean_absolute_error

# 5개 데이터의 실제값과 예측값
actual_values = np.array([100, 150, 120, 180, 90]) # ①
predicted_values = np.array([95, 160, 115, 175, 85]) # ②

# MAE 수동 계산
differences = actual_values - predicted_values # ③
absolute_differences = np.abs(differences) # ④
manual_mae = np.mean(absolute_differences) # ⑤
print(f"MAE: {manual_mae:.2f}")

# sklearn을 사용한 MAE 계산
sklearn_mae = mean_absolute_error(actual_values, predicted_values) # ⑥
print(f"MAE: {sklearn_mae:.2f}")

MAE: 6.00
MAE: 6.00


In [5]:
# T02_05.py
import numpy as np
from sklearn.metrics import mean_squared_error

# 5개 데이터의 실제값과 예측값
actual_values = np.array([100, 150, 120, 180, 90]) # ①
predicted_values = np.array([95, 160, 115, 175, 85]) # ②

# sklearn을 사용한 MSE 계산
mse = mean_squared_error(actual_values, predicted_values) # ③
rmse = np.sqrt(mse) # ④
print(f"MSE : {mse:.3f}")
print(f"RMSE : {rmse:.3f}")

MSE : 40.000
RMSE : 6.325


In [6]:
# T02_06.py
import numpy as np
from sklearn.metrics import r2_score

# 단순한 데이터셋
actual = np.array([2, 4, 6, 8, 10]) # ①
predicted = np.array([2.1, 3.9, 6.2, 7.8, 9.9]) # ②

# 평균 계산
actual_mean = np.mean(actual) # ③
print(f"실제값 평균: {actual_mean}")

# 전체 제곱합(SST) 계산
sst = np.sum((actual - actual_mean) ** 2) # ④
print(f"전체 제곱합: {sst}")

# 회귀 제곱합(SSR) 계산
ssr = np.sum((predicted - actual_mean) ** 2) # ⑤
print(f"회귀 제곱합: {ssr}")

# 오차 제곱합(SSE) 계산
sse = np.sum((actual - predicted) ** 2) # ⑥
print(f"오차 제곱합: {sse}")

# R^2 계산
r2 = 1 - (sse / sst) # ⑦
r2_sklearn = r2_score(actual, predicted) # ⑧
print(f"R^2: {r2:.4f}")
print(f"R^2: {r2_sklearn:.4f}")

실제값 평균: 6.0
전체 제곱합: 40.0
회귀 제곱합: 38.11
오차 제곱합: 0.1100000000000001
R^2: 0.9972
R^2: 0.9972


In [7]:
# T02_07.py
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# 가격 예측을 위한 샘플 데이터
np.random.seed(42)
n_samples = 200

# 다양한 스케일의 독립변수들
area = np.random.normal(30, 8, n_samples) # ①
floor = np.random.randint(1, 21, n_samples) # ②
age = np.random.randint(0, 31, n_samples) # ③
distance = np.random.exponential(500, n_samples) # ④

# 종속변수(가격)
price = (0.5 * area +
         0.02 * floor -
         0.03 * age -
         0.001 * distance +
         np.random.normal(0, 1, n_samples) + 5) # ⑤

# 데이터프레임 생성
df = pd.DataFrame({
  'area': area,
  'floor': floor,
  'age': age,
  'distance': distance,
  'price': price
})

print(df.describe().round(2)) # ⑥

# 독립변수와 종속변수 분리
X = df[['area', 'floor', 'age', 'distance']] # ⑦
y = df['price'] # ⑧

# 데이터 분리(훈련 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42) # ⑨

print(f"훈련 데이터: {X_train.shape[0]}개")
print(f"테스트 데이터: {X_test.shape[0]}개")

         area   floor     age  distance   price
count  200.00  200.00  200.00    200.00  200.00
mean    29.67   10.58   15.44    424.74   19.11
std      7.45    5.90    9.22    436.65    3.95
min      9.04    1.00    0.00      7.33    6.66
25%     24.36    5.00    7.00    111.14   16.44
50%     29.97   11.00   16.00    285.09   19.36
75%     34.01   16.00   24.00    553.39   21.82
max     51.76   20.00   30.00   2300.60   29.39
훈련 데이터: 160개
테스트 데이터: 40개


In [8]:
# T02_08.py
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

# 모델 생성 및 학습
multi_model = LinearRegression()
multi_model.fit(X_train, y_train) # ①

# 예측 수행
y_train_pred = multi_model.predict(X_train) # ②
y_test_pred = multi_model.predict(X_test) # ③

# 성능 지표 계산
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)
train_mae = mean_absolute_error(y_train, y_train_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

print(f"훈련 R^2: {train_r2:.3f}")
print(f"테스트 R^2: {test_r2:.3f}")
print(f"훈련 MAE: {train_mae:.3f}")
print(f"테스트 MAE: {test_mae:.3f}")

훈련 R^2: 0.936
테스트 R^2: 0.907
훈련 MAE: 0.771
테스트 MAE: 1.001


In [9]:
# T02_09.py
feature_names = ['area', 'floor', 'age', 'distance']
coefficients = multi_model.coef_
intercept = multi_model.intercept_

# 모델의 절편 및 각 변수별 회귀계수 출력
print(f"절편: {intercept:.3f}") # ①

# ② 각 변수의 회귀계수(coefficients) 값을 확인하여 변수 1단위 증가 시 가격의 증감 변화 파악

# 계수의 절댓값을 기준으로 한 변수 중요도 산출
importance_list = []
for i in range(len(feature_names)): # ③
 importance_list.append((feature_names[i], abs(coefficients[i])))

# 중요도 기준 내림차순 정렬
importance_ranking = sorted(importance_list, # ④
                            key=lambda x: x[1], reverse=True)
for i in range(len(importance_ranking)):
  feature, importance = importance_ranking[i]
  print(f"{feature}: {importance:.3f}")

절편: 5.245
area: 0.496
age: 0.032
floor: 0.025
distance: 0.001


In [10]:
# T02_10.py
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor # ①

# VIF 계산
vif_data = []
for i in range(X_train.shape[1]): # ②
  vif_value = variance_inflation_factor(X_train.values, i) # ③
  vif_data.append([X_train.columns[i], vif_value]) # ④

vif_df = pd.DataFrame(vif_data, columns=['x', 'vif'])
vif_df = vif_df.sort_values('vif', ascending=False)

print(vif_df) # ⑤

          x       vif
0      area  5.379635
1     floor  3.722415
2       age  3.357105
3  distance  1.920605


In [11]:
# T02_11.py
from sklearn.feature_selection import SequentialFeatureSelector # ①

sfs = SequentialFeatureSelector(
  multi_model,
  n_features_to_select=3,
  direction='forward',
  cv=5,
  scoring='r2'
) # ②

sfs.fit(X_train, y_train) # ③

selected_features = X_train.columns[sfs.get_support()] # ④
print("선택된 변수:", list(selected_features))

선택된 변수: ['area', 'age', 'distance']


In [12]:
# T02_12.py
from sklearn.feature_selection import SequentialFeatureSelector # ①

sfs = SequentialFeatureSelector(
  multi_model,
  n_features_to_select=2,
  direction='backward',
  cv=5,
  scoring='r2'
) # ②

sfs.fit(X_train, y_train) # ③

selected_features = X_train.columns[sfs.get_support()] # ④
print("선택된 변수:", list(selected_features))

선택된 변수: ['area', 'distance']


In [13]:
# T02_13.py
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

# 예시 데이터를 생성
x_values = np.array([3, 1, 5, 4, 2]) # ①

# 2차 다항식 변환을 수행
X_original = x_values.reshape(-1, 1) # ②
poly_transformer = PolynomialFeatures(degree=2) # ③
X_transformed = poly_transformer.fit_transform(X_original) # ④
print(X_transformed)

# 변환 결과를 확인
feature_names = poly_transformer.get_feature_names_out(['x']) # ⑤
print(feature_names)

[[ 1.  3.  9.]
 [ 1.  1.  1.]
 [ 1.  5. 25.]
 [ 1.  4. 16.]
 [ 1.  2.  4.]]
['1' 'x' 'x^2']


In [14]:
# T02_14.py
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score

# 비선형 관계 데이터를 생성
np.random.seed(42)
temperature = np.linspace(10, 40, 30) # ①
error_rate = 0.1 * (temperature - 25)**2 + 2 + np.random.normal(0, 0.5, 30) # ②
X = temperature.reshape(-1, 1)
y = error_rate

# 선형 모델
linear_model = LinearRegression() # ③
linear_model.fit(X, y) # ④
linear_pred = linear_model.predict(X) # ⑤
print(linear_model.intercept_)
print(linear_model.coef_)

# 2차 다항식 모델
poly_features = PolynomialFeatures(degree=2) # ⑥
X_poly = poly_features.fit_transform(X) # ⑦
poly_model = LinearRegression() # ⑧
poly_model.fit(X_poly, y) # ⑨
poly_pred = poly_model.predict(X_poly) # ⑩
print(poly_model.intercept_)
print(poly_model.coef_)

# 선형 모델과 2차 다항식 모델 비교
print(f"선형 모델 R^2: {r2_score(y, linear_pred)}") # ⑪
print(f"2차 다항식 모델 R^2: {r2_score(y, poly_pred)}") # ⑫

10.347772310782721
[-0.01698418]
65.7550201552147
[ 0.         -5.10182654  0.10169685]
선형 모델 R^2: 0.00043484068212062965
2차 다항식 모델 R^2: 0.9970316462764635


In [15]:
# T02_15.py
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# 실전 데이터 시뮬레이션(광고비와 매출 관계)
np.random.seed(42)
ad_budget = np.linspace(1, 20, 100) # ①
sales = -0.1 * (ad_budget - 10)**2 + 50 + np.random.normal(0, 3, 100) # ②
X = ad_budget.reshape(-1, 1) # ③
y = sales # ④

# 훈련/검증 데이터 분할
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42) # ⑤
for d in [1, 2, 3, 4, 5]: # ⑥
  # 다항식 변환을 수행
  poly_transformer = PolynomialFeatures(degree=d) # ⑦
  X_train_poly = poly_transformer.fit_transform(X_train) # ⑧
  X_val_poly = poly_transformer.transform(X_val) # ⑨

  # 모델을 학습
  model = LinearRegression() # ⑩
  model.fit(X_train_poly, y_train) # ⑪

  # 성능을 평가
  train_r2 = model.score(X_train_poly, y_train) # ⑫
  val_r2 = model.score(X_val_poly, y_val) # ⑬
  val_mae = mean_absolute_error(y_val, model.predict(X_val_poly)) # ⑭

  print(f"{d:2d} {train_r2:8.3f} {val_r2:7.3f} {val_mae:8.1f}")

 1    0.023  -0.037      2.7
 2    0.462   0.545      1.8
 3    0.494   0.544      1.8
 4    0.498   0.554      1.7
 5    0.499   0.547      1.8


In [16]:
# Q02_01.py
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

# 데이터 로드
diamonds = sns.load_dataset('diamonds') # ①

# 수치형 데이터만 선택(카테고리형 변수 제외)
X = diamonds.select_dtypes(include=['number']).drop('price', axis=1) # ②
y = diamonds['price']

# 데이터 확인
print(X.head())

# 학습/테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Train size: {X_train.shape}, Test size: {X_test.shape}") # ③

   carat  depth  table     x     y     z
0   0.23   61.5   55.0  3.95  3.98  2.43
1   0.21   59.8   61.0  3.89  3.84  2.31
2   0.23   56.9   65.0  4.05  4.07  2.31
3   0.29   62.4   58.0  4.20  4.23  2.63
4   0.31   63.3   58.0  4.34  4.35  2.75
Train size: (43152, 6), Test size: (10788, 6)


In [17]:
# Q02_02.py
from sklearn.linear_model import LinearRegression

# 모델 객체 생성
model = LinearRegression() # ①

# 모델 학습(fit)
model.fit(X_train, y_train) # ②

# 테스트 데이터에 대한 예측(predict)
y_pred = model.predict(X_test) # ③

# 예측 결과 샘플 확인
print("실제값(상위 5개):", np.array(y_test[:5]))
print("예측값(상위 5개):", y_pred[:5]) # ④

실제값(상위 5개): [ 559 2201 1238 1304 6901]
예측값(상위 5개): [  200.79413447  2361.44322401  1051.27692119  1229.92592305
 10035.10505409]


In [18]:
# Q02_03.py
from sklearn.metrics import mean_squared_error, r2_score

# MSE 계산
mse = mean_squared_error(y_test, y_pred) # ①

# RMSE 계산(MSE에 루트)
rmse = np.sqrt(mse) # ②

# R2 Score 계산
r2 = r2_score(y_test, y_pred) # ③
print(f"MSE: {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"R2 Score: {r2:.4f}")

MSE: 2242178.9041
RMSE: 1497.3907
R2 Score: 0.8590


In [19]:
# Q02_04.py
from sklearn.preprocessing import PolynomialFeatures

# 2차 다항식 변환(degree=2)
poly = PolynomialFeatures(degree=2, include_bias=False) # ①
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# 선형 회귀 모델 재학습
poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

# 예측 및 성능 평가
y_pred_poly = poly_model.predict(X_test_poly)
r2_poly = r2_score(y_test, y_pred_poly)
print(f"Linear Regression R2: {r2:.4f}")
print(f"Polynomial Regression (2nd degree) R2: {r2_poly:.4f}") # ②

Linear Regression R2: 0.8590
Polynomial Regression (2nd degree) R2: 0.8782


In [20]:
# Q02_05.py
from sklearn.linear_model import Ridge

# 릿지 모델 생성 및 학습(다항 변환된 데이터 사용)
ridge_model = Ridge(alpha=10.0) # ①
ridge_model.fit(X_train_poly, y_train) # ②

# 예측 및 성능 평가
y_pred_ridge = ridge_model.predict(X_test_poly) # ③
r2_ridge = r2_score(y_test, y_pred_ridge) # ④

print(f"Polynomial + Ridge Regression R2: {r2_ridge:.4f}")

Polynomial + Ridge Regression R2: 0.8777
